import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { parseSignatures, scoreSignature, usableSignatures } from "../ml/signatures";
import type { SpatialResult } from "../ml/spatialResult";

/**
 * The signature set shipped in signatures/ has to survive its own loader.
 *
 * It is generated by a Python script and read by TypeScript, which is exactly
 * the seam where a field quietly changes name and nobody notices until a user
 * picks the file and gets nothing.
 */
const raw: unknown = JSON.parse(readFileSync("signatures/ibd-colon.json", "utf8"));

describe("the shipped IBD/colon signatures", () => {
  it("parses, and says where it came from", () => {
    const set = parseSignatures(raw);
    expect(set.signatures.length).toBeGreaterThan(100);
    expect(set.source).toMatch(/CELLxGENE/);
    expect(set.source).toMatch(/colitis|Crohn/);
  });

  it("carries weights, because these were ranked rather than hand-listed", () => {
    const set = parseSignatures(raw);
    const weights = set.signatures.flatMap((s) => s.genes.map((g) => g.weight));
    expect(weights.every((w) => Number.isFinite(w) && w > 0)).toBe(true);
    // A hand-written list would be all 1s; these are log fold changes.
    expect(new Set(weights).size).toBeGreaterThan(100);
  });

  it("holds no mitochondrial or ribosomal genes", () => {
    /*
     * These track dissociation stress and sequencing depth, not cell identity,
     * and they top a fold-change ranking if they are not removed before it.
     * Metallothioneins (MT1G, MT2A) must survive — real genes, induced in
     * inflamed mucosa, and an over-eager MT filter takes them too.
     */
    const set = parseSignatures(raw);
    const genes = [...new Set(set.signatures.flatMap((s) => s.genes.map((g) => g.gene)))];
    const technical = genes.filter((g) =>
      /^(MT-|MT(ATP|CO|CYB|ND|RNR)\d|RP[SL][\dP]|RPSA$|MRP[SL]\d|ENSG\d|LINC[\d-])/.test(g));
    expect(technical).toEqual([]);
    expect(genes).toContain("MT2A");
  });

  it("names the markers a pathologist would expect", () => {
    const set = parseSignatures(raw);
    const top = (name: string, n = 12) =>
      set.signatures.find((s) => s.name.toLowerCase() === name)!.genes.slice(0, n).map((g) => g.gene);

    expect(top("goblet cell")).toEqual(expect.arrayContaining(["MUC2", "TFF3", "ZG16"]));
    expect(top("plasma cell")).toEqual(expect.arrayContaining(["JCHAIN", "MZB1"]));
    expect(top("fibroblast")).toEqual(expect.arrayContaining(["COL1A1", "COL3A1", "DCN"]));
    expect(top("paneth cell")).toEqual(expect.arrayContaining(["DEFA5", "DEFA6"]));
    expect(top("mast cell")).toEqual(expect.arrayContaining(["TPSAB1", "CPA3"]));
    expect(top("endothelial cell")).toEqual(expect.arrayContaining(["PLVAP"]));
  });

  it("scores against a map, and hides what a narrow map cannot cover", () => {
    const set = parseSignatures(raw);
    const genes = ["MUC2", "TFF3", "ZG16", "CLCA1", "AGR2", "FCGBP"];
    const patches = 12;
    const values = new Float32Array(patches * genes.length);
    // A gradient across the patches, so the score has somewhere to go.
    for (let i = 0; i < patches; i++)
      for (let g = 0; g < genes.length; g++) values[i * genes.length + g] = i + g * 0.1;

    const result = {
      slide: "s.svs", genes, values,
      patches: Array.from({ length: patches }, (_, i) => ({ x: i * 10, y: 0 })),
      side: 10, modelId: "t", modelName: "t", roiId: null, ms: 0,
      createdAt: new Date().toISOString(),
    } as unknown as SpatialResult;

    const usable = usableSignatures(result, set);
    expect(usable.length).toBeGreaterThan(0);
    // Six goblet genes cannot support 111 cell types.
    expect(usable.length).toBeLessThan(set.signatures.length);

    const goblet = set.signatures.find((s) => s.name.toLowerCase() === "goblet cell")!;
    const score = scoreSignature(result, goblet)!;
    expect(score).not.toBeNull();
    expect(score.length).toBe(patches);
    expect(score.every(Number.isFinite)).toBe(true);
    expect(score[patches - 1]).toBeGreaterThan(score[0]);
  });
});
