/**
 * Copy ONNX Runtime's wasm assets into public/ort.
 *
 * They have to be served from our own origin rather than a CDN: the app is
 * cross-origin isolated (COOP/COEP), which openslide-wasm requires for
 * SharedArrayBuffer, and under COEP a cross-origin script without the right
 * CORP header fails silently — the model simply never loads, with nothing in
 * the console to say why.
 *
 * They are vendor build artefacts, so they are fetched at install time rather
 * than committed: 97 MB in git makes the repository slow to clone for files
 * that npm already has.
 */
import { cp, mkdir, readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const from = join(root, "node_modules", "onnxruntime-web", "dist");
const to = join(root, "public", "ort");

if (!existsSync(from)) {
  console.error("onnxruntime-web is not installed; run npm install first.");
  process.exit(0); // not fatal: a fresh checkout runs this again after install
}

await mkdir(to, { recursive: true });

let copied = 0;
for (const name of await readdir(from)) {
  if (!/\.(wasm|mjs)$/.test(name)) continue;
  await cp(join(from, name), join(to, name));
  copied++;
}

await writeFile(
  join(to, "README.txt"),
  "Generated by scripts/setup-ort.mjs from node_modules/onnxruntime-web/dist.\n" +
    "Not checked in; run `npm install` (or `npm run setup:ort`) to recreate.\n",
);

console.log(`ort: copied ${copied} files into public/ort`);
